development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: john
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: john
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: john
  password: